version: '3.4'

services:
  bikeworkshop.database:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=myStong_Password123#
    volumes:
        - ./.containers/mssql:/var/opt/mssql    

  bikeworkshop.api:
    container_name: BikeWorkshopAPI
    image: ${DOCKER_REGISTRY-}bikeworkshopapi
    ports:
        - "5000:5000"
        - "5001:5001" 
    build:
      context: .
      dockerfile: BikeWorkshop.API/Dockerfile
    depends_on: 
    - bikeworkshop.database