version: '3.4'

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=myStong_Password123#    

  bikeworkshop.api:
    container_name: BikeWorkshopAPI
    image: ${DOCKER_REGISTRY-}bikeworkshopapi
    ports:
        - 8001:80
    build:
      context: .
      dockerfile: BikeWorkshop.API/Dockerfile
    depends_on: 
    - SqlServerDb