name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
   DOTNET_VERSION: "8.0.x"

jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
         - uses: actions/checkout@v3

         - name: Setup
           uses: actions/setup-dotnet@v3
           with:
              dotnet-version: ${{ env.DOTNET_VERSION }}        

         - name: Restore
           run: dotnet restore ./BikeWorkshop.sln
         
         - name: Build
           run: dotnet build ./BikeWorkshop.sln --configuration Release --no-restore

         - name: Test
           run: dotnet test ./BikeWorkshop.sln --configuration Release --no-restore --no-build
